// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: tts/v1/inference.proto

package ttsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTSInference_Health_FullMethodName         = "/tts.v1.TTSInference/Health"
	TTSInference_Synthesize_FullMethodName     = "/tts.v1.TTSInference/Synthesize"
	TTSInference_SynthesizeLive_FullMethodName = "/tts.v1.TTSInference/SynthesizeLive"
)

// TTSInferenceClient is the client API for TTSInference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSInferenceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	SynthesizeLive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveTextChunk, AudioChunk], error)
}

type tTSInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSInferenceClient(cc grpc.ClientConnInterface) TTSInferenceClient {
	return &tTSInferenceClient{cc}
}

func (c *tTSInferenceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TTSInference_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tTSInferenceClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSInference_ServiceDesc.Streams[0], TTSInference_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSInference_SynthesizeClient = grpc.ServerStreamingClient[AudioChunk]

func (c *tTSInferenceClient) SynthesizeLive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveTextChunk, AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSInference_ServiceDesc.Streams[1], TTSInference_SynthesizeLive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LiveTextChunk, AudioChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSInference_SynthesizeLiveClient = grpc.BidiStreamingClient[LiveTextChunk, AudioChunk]

// TTSInferenceServer is the server API for TTSInference service.
// All implementations must embed UnimplementedTTSInferenceServer
// for forward compatibility.
type TTSInferenceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error
	SynthesizeLive(grpc.BidiStreamingServer[LiveTextChunk, AudioChunk]) error
	mustEmbedUnimplementedTTSInferenceServer()
}

// UnimplementedTTSInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSInferenceServer struct{}

func (UnimplementedTTSInferenceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTTSInferenceServer) Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedTTSInferenceServer) SynthesizeLive(grpc.BidiStreamingServer[LiveTextChunk, AudioChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeLive not implemented")
}
func (UnimplementedTTSInferenceServer) mustEmbedUnimplementedTTSInferenceServer() {}
func (UnimplementedTTSInferenceServer) testEmbeddedByValue()                      {}

// UnsafeTTSInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSInferenceServer will
// result in compilation errors.
type UnsafeTTSInferenceServer interface {
	mustEmbedUnimplementedTTSInferenceServer()
}

func RegisterTTSInferenceServer(s grpc.ServiceRegistrar, srv TTSInferenceServer) {
	// If the following call pancis, it indicates UnimplementedTTSInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSInference_ServiceDesc, srv)
}

func _TTSInference_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSInferenceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSInference_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSInferenceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TTSInference_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSInferenceServer).Synthesize(m, &grpc.GenericServerStream[SynthesizeRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSInference_SynthesizeServer = grpc.ServerStreamingServer[AudioChunk]

func _TTSInference_SynthesizeLive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSInferenceServer).SynthesizeLive(&grpc.GenericServerStream[LiveTextChunk, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSInference_SynthesizeLiveServer = grpc.BidiStreamingServer[LiveTextChunk, AudioChunk]

// TTSInference_ServiceDesc is the grpc.ServiceDesc for TTSInference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tts.v1.TTSInference",
	HandlerType: (*TTSInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TTSInference_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _TTSInference_Synthesize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeLive",
			Handler:       _TTSInference_SynthesizeLive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tts/v1/inference.proto",
}
